[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "lift-logger"
dynamic = ["version"]
description = "A python application for logging workouts and tracking progress."
readme = "README.md"
requires-python = ">=3.8"
license = { file = "LICENSE" }
authors = [
  { name = "Tyson Westendorf", email = "tywestendorf@gmail.com" },
]
keywords = ["example", "python", "package"]
dependencies = [
    "textual",
]
[project.urls]
Homepage = "https://github.com/TWestendorf19/python-lift-logger"
Repository = "https://github.com/TWestendorf19/python-lift-logger"
Issues = "https://github.com/TWestendorf/python-lift-logger/issues"

[tool.setuptools.dynamic]
version = {attr = "lift_logger.__version__"}

[project.scripts]
liftlogger = "lift_logger.main:main"
